# docker-compose.yml
version: '3.8'

services:
  minecraft:
    image: itzg/minecraft-server
    container_name: minecraft
    hostname: minecraft
    restart: unless-stopped

    # Load all server settings from the .env file
    env_file: .env

    # Expose ports on your LAN
    ports:
      - "25565:25565"   # Minecraft server
      - "8100:8100"     # Bluemap (optional)
      - "8123:8123"     # Dynmap (optional)

    # Persist world & config data
    volumes:
      - ./minecraft_data:/data

    # Keep STDIN open so you can exec into the container if needed
    tty: true
    stdin_open: true

    # Basic log rotation to avoid filling up disk
    logging:
      driver: json-file
      options:
        max-size: "50m"
        max-file: "5"

